<?php


// Here's what the result would look like with your data:
$postCodeArray = array(
   'BR11AA' => array(
    'Flat 38, Henry House, Ringers Road',
    'Flat 27, Henry House, Ringers Road',
    'Flat 28, Henry House, Ringers Road',
    'Flat 29, Henry House, Ringers Road',
    'Flat 30, Henry House, Ringers Road',
    'Flat 31, Henry House, Ringers Road',
    'Flat 32, Henry House, Ringers Road',
    'Flat 33, Henry House, Ringers Road',
    'Flat 34, Henry House, Ringers Road',
    'Flat 35, Henry House, Ringers Road',
    'Flat 36, Henry House, Ringers Road',
    'Flat 37, Henry House, Ringers Road',
    'Flat 26, Henry House, Ringers Road',
    'Flat 39, Henry House, Ringers Road',
    'Flat 40, Henry House, Ringers Road',
    'Flat 41, Henry House, Ringers Road',
    'Flat 42, Henry House, Ringers Road',
    'Flat 43, Henry House, Ringers Road',
    'Flat 44, Henry House, Ringers Road',
    'Flat 45, Henry House, Ringers Road',
    'Flat 46, Henry House, Ringers Road',
    'Flat 47, Henry House, Ringers Road',
    'Flat 48, Henry House, Ringers Road',
    'Flat 49, Henry House, Ringers Road',
    'Flat 14, Henry House, Ringers Road',
    'Flat 2, Henry House, Ringers Road',
    'Flat 3, Henry House, Ringers Road',
    'Flat 4, Henry House, Ringers Road',
    'Flat 5, Henry House, Ringers Road',
    'Flat 6, Henry House, Ringers Road',
    'Flat 7, Henry House, Ringers Road',
    'Flat 8, Henry House, Ringers Road',
    'Flat 9, Henry House, Ringers Road',
    'Flat 10, Henry House, Ringers Road',
    'Flat 11, Henry House, Ringers Road',
    'Flat 12, Henry House, Ringers Road',
    'Flat 1, Henry House, Ringers Road',
    'Flat 15, Henry House, Ringers Road',
    'Flat 16, Henry House, Ringers Road',
    'Flat 17, Henry House, Ringers Road',
    'Flat 18, Henry House, Ringers Road',
    'Flat 19, Henry House, Ringers Road',
    'Flat 20, Henry House, Ringers Road',
    'Flat 21, Henry House, Ringers Road',
    'Flat 22, Henry House, Ringers Road',
    'Flat 23, Henry House, Ringers Road',
    'Flat 24, Henry House, Ringers Road',
    'Flat 25, Henry House, Ringers Road'
),
    'BR11AB' => array(
    'Apartment 1, The Old Post Office 3B, East Street',
    'Apartment 2, The Old Post Office 3B, East Street',
    'Apartment 3, The Old Post Office 3B, East Street',
    'Apartment 4, The Old Post Office 3B, East Street',
    'Apartment 5, The Old Post Office 3B, East Street',
    'Apartment 6, The Old Post Office 3B, East Street',
    'Apartment 7, The Old Post Office 3B, East Street',
    'Apartment 8, The Old Post Office 3B, East Street',
    '3 East Street',
    'Bird & Bun Rotisserie, 3A, East Street'
),
'BR11AE' => array(
    'Flat 13, Hawksworth House, Tetty Way',
    'Flat 24, Hawksworth House, Tetty Way',
    'Flat 23, Hawksworth House, Tetty Way',
    'Flat 22, Hawksworth House, Tetty Way',
    'Flat 21, Hawksworth House, Tetty Way',
    'Flat 20, Hawksworth House, Tetty Way',
    'Flat 19, Hawksworth House, Tetty Way',
    'Flat 18, Hawksworth House, Tetty Way',
    'Flat 17, Hawksworth House, Tetty Way',
    'Flat 16, Hawksworth House, Tetty Way',
    'Flat 15, Hawksworth House, Tetty Way',
    'Flat 14, Hawksworth House, Tetty Way',
    'Flat 1, Hawksworth House, Tetty Way',
    'Flat 12, Hawksworth House, Tetty Way',
    'Flat 11, Hawksworth House, Tetty Way',
    'Flat 10, Hawksworth House, Tetty Way',
    'Flat 9, Hawksworth House, Tetty Way',
    'Flat 8, Hawksworth House, Tetty Way',
    'Flat 7, Hawksworth House, Tetty Way',
    'Flat 6, Hawksworth House, Tetty Way',
    'Flat 5, Hawksworth House, Tetty Way',
    'Flat 4, Hawksworth House, Tetty Way',
    'Flat 3, Hawksworth House, Tetty Way',
    'Flat 2, Hawksworth House, Tetty Way'
),
'BR11AF' => array(
    'Flat 44, William House, Ringers Road',
    'Flat 31, William House, Ringers Road',
    'Flat 32, William House, Ringers Road',
    'Flat 33, William House, Ringers Road',
    'Flat 34, William House, Ringers Road',
    'Flat 35, William House, Ringers Road',
    'Flat 36, William House, Ringers Road',
    'Flat 37, William House, Ringers Road',
    'Flat 38, William House, Ringers Road',
    'Flat 39, William House, Ringers Road',
    'Flat 40, William House, Ringers Road',
    'Flat 41, William House, Ringers Road',
    'Flat 42, William House, Ringers Road',
    'Flat 43, William House, Ringers Road',
    'Flat 30, William House, Ringers Road',
    'Flat 45, William House, Ringers Road',
    'Flat 46, William House, Ringers Road',
    'Flat 47, William House, Ringers Road',
    'Flat 48, William House, Ringers Road',
    'Flat 49, William House, Ringers Road',
    'Flat 50, William House, Ringers Road',
    'Flat 51, William House, Ringers Road',
    'Flat 52, William House, Ringers Road',
    'Flat 53, William House, Ringers Road',
    'Flat 54, William House, Ringers Road',
    'Flat 55, William House, Ringers Road',
    'Flat 56, William House, Ringers Road',
    'Flat 57, William House, Ringers Road',
    'Flat 16, William House, Ringers Road',
    'Flat 2, William House, Ringers Road',
    'Flat 3, William House, Ringers Road',
    'Flat 4, William House, Ringers Road',
    'Flat 5, William House, Ringers Road',
    'Flat 6, William House, Ringers Road',
    'Flat 7, William House, Ringers Road',
    'Flat 8, William House, Ringers Road',
    'Flat 9, William House, Ringers Road',
    'Flat 10, William House, Ringers Road',
    'Flat 11, William House, Ringers Road',
    'Flat 12, William House, Ringers Road',
    'Flat 14, William House, Ringers Road',
    'Flat 15, William House, Ringers Road',
    'Flat 1, William House, Ringers Road',
    'Flat 17, William House, Ringers Road',
    'Flat 18, William House, Ringers Road',
    'Flat 19, William House, Ringers Road',
    'Flat 20, William House, Ringers Road',
    'Flat 21, William House, Ringers Road',
    'Flat 22, William House, Ringers Road',
    'Flat 23, William House, Ringers Road',
    'Flat 24, William House, Ringers Road',
    'Flat 25, William House, Ringers Road',
    'Flat 26, William House, Ringers Road',
    'Flat 27, William House, Ringers Road',
    'Flat 28, William House, Ringers Road',
    'Flat 29, William House, Ringers Road'
),
'BR11AG' => array(
    'Flat 100, William House, Ringers Road',
    'Flat 87, William House, Ringers Road',
    'Flat 88, William House, Ringers Road',
    'Flat 89, William House, Ringers Road',
    'Flat 90, William House, Ringers Road',
    'Flat 91, William House, Ringers Road',
    'Flat 92, William House, Ringers Road',
    'Flat 93, William House, Ringers Road',
    'Flat 94, William House, Ringers Road',
    'Flat 95, William House, Ringers Road',
    'Flat 96, William House, Ringers Road',
    'Flat 97, William House, Ringers Road',
    'Flat 98, William House, Ringers Road',
    'Flat 99, William House, Ringers Road',
    'Flat 86, William House, Ringers Road',
    'Flat 101, William House, Ringers Road',
    'Flat 102, William House, Ringers Road',
    'Flat 103, William House, Ringers Road',
    'Flat 104, William House, Ringers Road',
    'Flat 105, William House, Ringers Road',
    'Flat 106, William House, Ringers Road',
    'Flat 107, William House, Ringers Road',
    'Flat 108, William House, Ringers Road',
    'Flat 109, William House, Ringers Road',
    'Flat 110, William House, Ringers Road',
    'Flat 111, William House, Ringers Road',
    'Flat 112, William House, Ringers Road',
    'Flat 113, William House, Ringers Road',
    'Flat 72, William House, Ringers Road',
    'Flat 59, William House, Ringers Road',
    'Flat 60, William House, Ringers Road',
    'Flat 61, William House, Ringers Road',
    'Flat 62, William House, Ringers Road',
    'Flat 63, William House, Ringers Road',
    'Flat 64, William House, Ringers Road',
    'Flat 65, William House, Ringers Road',
    'Flat 66, William House, Ringers Road',
    'Flat 67, William House, Ringers Road',
    'Flat 68, William House, Ringers Road',
    'Flat 69, William House, Ringers Road',
    'Flat 70, William House, Ringers Road',
    'Flat 71, William House, Ringers Road',
    'Flat 58, William House, Ringers Road',
    'Flat 73, William House, Ringers Road',
    'Flat 74, William House, Ringers Road',
    'Flat 75, William House, Ringers Road',
    'Flat 76, William House, Ringers Road',
    'Flat 77, William House, Ringers Road',
    'Flat 78, William House, Ringers Road',
    'Flat 79, William House, Ringers Road',
    'Flat 80, William House, Ringers Road',
    'Flat 81, William House, Ringers Road',
    'Flat 82, William House, Ringers Road',
    'Flat 83, William House, Ringers Road',
    'Flat 84, William House, Ringers Road',
    'Flat 85, William House, Ringers Road'
),
'BR11AH' => array(
    'Flat 34, Broadway House, 3 High Street',
    'Flat 24, Broadway House, 3 High Street',
    'Flat 25, Broadway House, 3 High Street',
    'Flat 26, Broadway House, 3 High Street',
    'Flat 27, Broadway House, 3 High Street',
    'Flat 28, Broadway House, 3 High Street',
    'Flat 29, Broadway House, 3 High Street',
    'Flat 30, Broadway House, 3 High Street',
    'Flat 31, Broadway House, 3 High Street',
    'Flat 32, Broadway House, 3 High Street',
    'Flat 33, Broadway House, 3 High Street',
    'Flat 2, Broadway House, 3 High Street',
    'Flat 35, Broadway House, 3 High Street',
    'Flat 36, Broadway House, 3 High Street',
    'Flat 37, Broadway House, 3 High Street',
    'Flat 38, Broadway House, 3 High Street',
    'Flat 39, Broadway House, 3 High Street',
    'Flat 40, Broadway House, 3 High Street',
    'Flat 41, Broadway House, 3 High Street',
    'Flat 42, Broadway House, 3 High Street',
    'Flat 43, Broadway House, 3 High Street',
    'Flat 44, Broadway House, 3 High Street',
    'Flat 22, Broadway House, 3 High Street',
    'Flat 1, Broadway House, 3 High Street',
    'Flat 3, Broadway House, 3 High Street',
    'Flat 4, Broadway House, 3 High Street',
    'Flat 5, Broadway House, 3 High Street',
    'Flat 6, Broadway House, 3 High Street',
    'Flat 7, Broadway House, 3 High Street',
    'Flat 8, Broadway House, 3 High Street',
    'Flat 9, Broadway House, 3 High Street',
    'Flat 10, Broadway House, 3 High Street',
    'Flat 11, Broadway House, 3 High Street',
    'Flat 12, Broadway House, 3 High Street',
    'Flat 14, Broadway House, 3 High Street',
    'Flat 15, Broadway House, 3 High Street',
    'Flat 16, Broadway House, 3 High Street',
    'Flat 17, Broadway House, 3 High Street',
    'Flat 18, Broadway House, 3 High Street',
    'Flat 19, Broadway House, 3 High Street',
    'Flat 20, Broadway House, 3 High Street',
    'Flat 21, Broadway House, 3 High Street',
    'Flat 23, Broadway House, 3 High Street',
    'Jeba Baiga, Flat 32, Broadway House, 3 High Street'
),
'BR11AJ' => array(
    'Flat 39, Nexus Apartments, 39 Elmfield Road',
    'Flat 27, Nexus Apartments, 39 Elmfield Road',
    'Flat 28, Nexus Apartments, 39 Elmfield Road',
    'Flat 29, Nexus Apartments, 39 Elmfield Road',
    'Flat 30, Nexus Apartments, 39 Elmfield Road',
    'Flat 31, Nexus Apartments, 39 Elmfield Road',
    'Flat 32, Nexus Apartments, 39 Elmfield Road',
    'Flat 33, Nexus Apartments, 39 Elmfield Road',
    'Flat 34, Nexus Apartments, 39 Elmfield Road',
    'Flat 35, Nexus Apartments, 39 Elmfield Road',
    'Flat 36, Nexus Apartments, 39 Elmfield Road',
    'Flat 37, Nexus Apartments, 39 Elmfield Road',
    'Flat 38, Nexus Apartments, 39 Elmfield Road',
    'Flat 26, Nexus Apartments, 39 Elmfield Road',
    'Flat 40, Nexus Apartments, 39 Elmfield Road',
    'Flat 41, Nexus Apartments, 39 Elmfield Road',
    'Flat 42, Nexus Apartments, 39 Elmfield Road',
    'Flat 43, Nexus Apartments, 39 Elmfield Road',
    'Flat 44, Nexus Apartments, 39 Elmfield Road',
    'Flat 45, Nexus Apartments, 39 Elmfield Road',
    'Flat 46, Nexus Apartments, 39 Elmfield Road',
    'Flat 47, Nexus Apartments, 39 Elmfield Road',
    'Flat 48, Nexus Apartments, 39 Elmfield Road',
    'Flat 49, Nexus Apartments, 39 Elmfield Road',
    'Flat 50, Nexus Apartments, 39 Elmfield Road',
    'Flat 14, Nexus Apartments, 39 Elmfield Road',
    'Flat 2, Nexus Apartments, 39 Elmfield Road',
    'Flat 3, Nexus Apartments, 39 Elmfield Road',
    'Flat 4, Nexus Apartments, 39 Elmfield Road',
    'Flat 5, Nexus Apartments, 39 Elmfield Road',
    'Flat 6, Nexus Apartments, 39 Elmfield Road',
    'Flat 7, Nexus Apartments, 39 Elmfield Road',
    'Flat 8, Nexus Apartments, 39 Elmfield Road',
    'Flat 9, Nexus Apartments, 39 Elmfield Road',
    'Flat 10, Nexus Apartments, 39 Elmfield Road',
    'Flat 11, Nexus Apartments, 39 Elmfield Road',
    'Flat 12, Nexus Apartments, 39 Elmfield Road',
    'Flat 13, Nexus Apartments, 39 Elmfield Road',
    'Flat 1, Nexus Apartments, 39 Elmfield Road',
    'Flat 15, Nexus Apartments, 39 Elmfield Road',
    'Flat 16, Nexus Apartments, 39 Elmfield Road',
    'Flat 17, Nexus Apartments, 39 Elmfield Road',
    'Flat 18, Nexus Apartments, 39 Elmfield Road',
    'Flat 19, Nexus Apartments, 39 Elmfield Road',
    'Flat 20, Nexus Apartments, 39 Elmfield Road',
    'Flat 21, Nexus Apartments, 39 Elmfield Road',
    'Flat 22, Nexus Apartments, 39 Elmfield Road',
    'Flat 23, Nexus Apartments, 39 Elmfield Road',
    'Flat 24, Nexus Apartments, 39 Elmfield Road',
    'Flat 25, Nexus Apartments, 39 Elmfield Road'
),
'BR11AL' => array(
    'Flat 1, Wyn House, 4 Walters Yard',
    'Flat 2, Wyn House, 4 Walters Yard',
    'Flat 3, Wyn House, 4 Walters Yard',
    'Flat 4, Wyn House, 4 Walters Yard',
    'Flat 5, Wyn House, 4 Walters Yard',
    'Flat 6, Wyn House, 4 Walters Yard',
    'Flat 7, Wyn House, 4 Walters Yard',
    'Flat 8, Wyn House, 4 Walters Yard'
),
'BR11BQ' =>array(
        'Flat 1, Newman Court, North Street',
        'Flat 2, Newman Court, North Street',
        'Flat 3, Newman Court, North Street',
        'Flat 4, Newman Court, North Street',
        'Flat 5, Newman Court, North Street',
        'Flat 6, Newman Court, North Street',
        'Flat 7, Newman Court, North Street',
        'Flat 8, Newman Court, North Street',
        'Flat 9, Newman Court, North Street',
        'Flat 10, Newman Court, North Street',
        'Flat 11, Newman Court, North Street',
        'Flat 12, Newman Court, North Street',
        'Flat 14, Newman Court, North Street',
        'Flat 15, Newman Court, North Street',
        'Flat 16, Newman Court, North Street',
        'Flat 17, Newman Court, North Street',
        'Flat 18, Newman Court, North Street',
        'Flat 19, Newman Court, North Street',
        'Flat 20, Newman Court, North Street',
        'Flat 21, Newman Court, North Street',
        'Flat 22, Newman Court, North Street',
        'Flat 23, Newman Court, North Street',
        'Flat 24, Newman Court, North Street',
        'Flat 25, Newman Court, North Street',
        'Flat 26, Newman Court, North Street',
        'Flat 27, Newman Court, North Street',
        'Flat 28, Newman Court, North Street',
        'Flat 29, Newman Court, North Street',
        'Flat 30, Newman Court, North Street',
        'Flat 31, Newman Court, North Street',
        'Flat 32, Newman Court, North Street',
        'Flat 33, Newman Court, North Street',
        'Flat 34, Newman Court, North Street',
        'Flat 35, Newman Court, North Street',
        'Flat 36, Newman Court, North Street',
        'Flat 37, Newman Court, North Street',
        'Flat 38, Newman Court, North Street',
        'Flat 39, Newman Court, North Street',
        'Flat 40, Newman Court, North Street'
);
'BR11BW' =>array(
    'Direct Line Insurance plc, Churchill Court, Westmoreland Road'
),
'BR11BY' =>array(
        'London Road, Bromley - More Addresses'
),
'BR11BZ' =>array(
    'Flat 1, Crocus House, Carrington Close',
    'Flat 2, Crocus House, Carrington Close',
    'Flat 3, Crocus House, Carrington Close',
    'Flat 4, Crocus House, Carrington Close',
    'Flat 5, Crocus House, Carrington Close',
    'Flat 6, Crocus House, Carrington Close',
    'Flat 7, Crocus House, Carrington Close',
    'Flat 8, Crocus House, Carrington Close'
),
'BR11DD' => array(
    'Caffe Nero, 1 The Glades Shopping Centre High Street',
    'Caffe Nero, Intu Bromley, 1 The Glades Shopping Centre High Street',
    'Rituals, 2 The Glades Shopping Centre High Street',
    'Rituals, Intu Bromley, 2 The Glades Shopping Centre High Street',
    'The Body Shop International plc, 5 The Glades Shopping Centre High Street',
    'The Body Shop International plc, Intu Bromley, 5 The Glades Shopping Centre High Street',
    '6 The Glades Shopping Centre High Street',
    'Intu Bromley, 6 The Glades Shopping Centre High Street',
    'Game Stores Group Ltd, Intu Bromley, 12 The Glades Shopping Centre High Street',
    'Game Stores Group Ltd, 12 The Glades Shopping Centre High Street',
    'Mac, 13 The Glades Shopping Centre High Street',
    'Mac, Intu Bromley, 13 The Glades Shopping Centre High Street',
    'L\'occitane, Intu Bromley, 14 The Glades Shopping Centre High Street',
    'L\'occitane, 14 The Glades Shopping Centre High Street',
    '15 The Glades Shopping Centre High Street',
    '16 The Glades Shopping Centre High Street',
    'Fraser Hart Ltd, Intu Bromley, 17 The Glades Shopping Centre High Street',
    'Fraser Hart Ltd, 17 The Glades Shopping Centre High Street',
    'Laser Clinic U K, Intu Bromley, 18 The Glades Shopping Centre High Street',
    'Laser Clinic U K, 18 The Glades Shopping Centre High Street',
    'Boost Juice Bar, 20 The Glades Shopping Centre High Street',
    'Boost Juice Bar, Intu Bromley, 20 The Glades Shopping Centre High Street',
    'Swarovski, 21 The Glades Shopping Centre High Street',
    'Swarovski, Intu Bromley, 21 The Glades Shopping Centre High Street',
    'Tech House, Intu Bromley, 22 The Glades Shopping Centre High Street',
    'Tech House, 22 The Glades Shopping Centre High Street',
    'The Perfume Shop, 23 The Glades Shopping Centre High Street',
    'The Perfume Shop, Intu Bromley, 23 The Glades Shopping Centre High Street',
    'Intu Bromley, 24 The Glades Shopping Centre High Street',
    '24 The Glades Shopping Centre High Street',
    'Auntie Annes, Intu Bromley, 25 The Glades Shopping Centre High Street',
    'Auntie Annes, 25 The Glades Shopping Centre High Street',
    'O2, Intu Bromley, 27 The Glades Shopping Centre High Street',
    'O2, 27 The Glades Shopping Centre High Street',
    'Telefonica O2 UK Ltd, 27 The Glades Shopping Centre High Street',
    'Costa Coffee, Intu Bromley, 28 The Glades Shopping Centre High Street',
    'Costa Coffee, 28 The Glades Shopping Centre High Street',
    'Vision Express (UK) Ltd, Intu Bromley, 29 The Glades Shopping Centre High Street',
    'Vision Express (UK) Ltd, 29 The Glades Shopping Centre High Street',
    '30 The Glades Shopping Centre High Street',
    'Intu Bromley, 30 The Glades Shopping Centre High Street',
    'Partica Bromley Ltd, Intu Bromley, 31 The Glades Shopping Centre High Street',
    'Partica Bromley Ltd, 31 The Glades Shopping Centre High Street',
    'The Entertainer Toy Shop, Intu Bromley, 33 The Glades Shopping Centre High Street',
    'The Entertainer Toy Shop, 33 The Glades Shopping Centre High Street',
    'Intu Bromley, 34 The Glades Shopping Centre High Street',
    '34 The Glades Shopping Centre High Street',
    'Works Shop, Intu Bromley, 35 The Glades Shopping Centre High Street',
    'Works Shop, 35 The Glades Shopping Centre High Street',
    '36 The Glades Shopping Centre High Street',
    'Intu Bromley, 36 The Glades Shopping Centre High Street',
    'Intu Bromley, 39 The Glades Shopping Centre High Street',
    '39 The Glades Shopping Centre High Street',
    'Boots Dentalcare, Intu Bromley, 40 The Glades Shopping Centre High Street',
    'Boots Dentalcare, Unit 66, 40 The Glades Shopping Centre High Street',
    'Boots Dentalcare, 40 The Glades Shopping Centre High Street',
    'Boots the Chemists Ltd, 40 The Glades Shopping Centre High Street',
    'Rush Hair, 40 The Glades Shopping Centre High Street',
    'Time For Pets, 44 The Glades Shopping Centre High Street',
    'Time For Pets, Intu Bromley, 44 The Glades Shopping Centre High Street',
    'Patisserie Valerie, Intu Bromley, 45 The Glades Shopping Centre High Street',
    'Patisserie Valerie, 45 The Glades Shopping Centre High Street',
    'Bromley Eye Centre Ltd, Intu Bromley, 48 The Glades Shopping Centre High Street',
    'Bromley Eye Centre Ltd, 48 The Glades Shopping Centre High Street',
    'Soletrader, 49 The Glades Shopping Centre High Street',
    '50 The Glades Shopping Centre High Street',
    'Intu Bromley, 50 The Glades Shopping Centre High Street',
    'Men Kind, Intu Bromley, 51 The Glades Shopping Centre High Street',
    'Men Kind, 51 The Glades Shopping Centre High Street',
    'Vodafone, 52 The Glades Shopping Centre High Street',
    'Vodafone, Intu Bromley, 52 The Glades Shopping Centre High Street',
    'Ernest Jones, Intu Bromley, 53 The Glades Shopping Centre High Street',
    'Ernest Jones, 53 The Glades Shopping Centre High Street',
    '57 The Glades Shopping Centre High Street',
    'Intu Bromley, 57 The Glades Shopping Centre High Street',
    'Ann Summers, 58 The Glades Shopping Centre High Street',
    'E E, 59 The Glades Shopping Centre High Street',
    'E E, Intu Bromley, 59 The Glades Shopping Centre High Street',
    'Footlocker, 60 The Glades Shopping Centre High Street',
    'Footlocker, Intu Bromley, 60 The Glades Shopping Centre High Street',
    'H Samuel Ltd, 61 The Glades Shopping Centre High Street',
    'H Samuel Ltd, Intu Bromley, 61 The Glades Shopping Centre High Street',
    'Superdrug Stores plc, Intu Bromley, 67 The Glades Shopping Centre High Street',
    'Superdrug Stores plc, 67 The Glades Shopping Centre High Street',
    'The Fragrance Shop, 68 The Glades Shopping Centre High Street',
    'The Fragrance Shop, Intu Bromley, 68 The Glades Shopping Centre High Street',
    'Claires Accessories, 69 The Glades Shopping Centre High Street',
    'Claires Accessories, Intu Bromley, 69 The Glades Shopping Centre High Street',
    'Hotel Chocolat, 72 The Glades Shopping Centre High Street',
    'Glades Retail Ltd, Intu Bromley, 73 The Glades Shopping Centre High Street',
    'Glades Retail Ltd, 73 The Glades Shopping Centre High Street',
    'Unique Hair, Intu Bromley, 74 The Glades Shopping Centre High Street',
    'Unique Hair, Regent Arcade, 74 The Glades Shopping Centre High Street',
    'Bare Necessities, Regent Arcade, 76 The Glades Shopping Centre High Street',
    'Bare Necessities, Intu Bromley, 76 The Glades Shopping Centre High Street',
    'And Cut Male Hair & Grooming, Intu Bromley, 77 The Glades Shopping Centre High Street',
    'And Cut Male Hair & Grooming, Regent Arcade, 77 The Glades Shopping Centre High Street',
    'Pompom Baby & Kidswear, Regent Arcade, 80 The Glades Shopping Centre High Street',
    'Pompom Baby & Kidswear, Intu Bromley, 80 The Glades Shopping Centre High Street',
    'Intu Bromley, 81 The Glades Shopping Centre High Street'
),
'BR11DE' => array(
    'Claritas Group, 15-17, London Road',
    'Eleanor Care, 15-17, London Road',
    'Hanson Regan Ltd, 15-17, London Road',
    'Novellus Capital Ltd, 15-17, London Road',
    'R S M, 15-17, London Road',
    'T-Bromley Assoc, 15-17, London Road',
    'Thackray Williams, 15-17, London Road',
    'Trust Payments, 15-17, London Road'
),
'BR11DG' => array(
    '37A, London Road',
    'Flat 1, 27 London Road',
    'Flat 10, 27 London Road',
    'Flat 9, 27 London Road',
    'Flat 8, 27 London Road',
    'Flat 7, 27 London Road',
    'Flat 6, 27 London Road',
    'Flat 2, 27 London Road',
    'Flat 5, 27 London Road',
    'Flat 4, 27 London Road',
    'Flat 3, 27 London Road',
    'Kesar & Co Ltd, 27 London Road',
    'B W A (Europe) Ltd, Alliance House, 29 London Road',
    'Bromley Mind, Alliance House, 29 London Road',
    'Go Train Ltd, Alliance House, 29 London Road',
    'Just Construction Recruitment Ltd, Alliance House, 29 London Road',
    'R G I S Inventory Specialists Ltd, Alliance House, 29 London Road',
    'Sarah Buckley Therapies Ltd, Alliance House, 29 London Road',
    'Twin Employment & Training, Alliance House, 29 London Road',
    'Albany House, 31 London Road',
    'Flat 8, 33 London Road',
    'Flat 7, 33 London Road',
    'Flat 6, 33 London Road',
    'Flat 5, 33 London Road',
    'Flat 4, 33 London Road',
    'Flat 3, 33 London Road',
    'Flat 2, 33 London Road',
    'Flat 1, 33 London Road',
    'Bromley United Services Club, 33 London Road',
    'Cleverbox, 33 London Road',
    'Bromley Community Drug Project, 35 London Road',
    'Travelodge Hotels Ltd, 37 London Road',
    'Kwik-Fit, 39-41, London Road'
),
'BR11DJ'=> array(
    'Waterstones, 100 The Glades Shopping Centre High Street',
    'Waterstones, Intu Bromley, 100 The Glades Shopping Centre High Street',
    '104 The Glades Shopping Centre High Street',
    'Unit 4 A3, 104 The Glades Shopping Centre High Street',
    '105 The Glades Shopping Centre High Street',
    'Unit 5 A3, 105 The Glades Shopping Centre High Street'
),
'BR11DN' => array(
    'New Look, 200 The Glades Shopping Centre High Street',
    '202 The Glades Shopping Centre High Street',
    '209 The Glades Shopping Centre High Street',
    'Lush Retail Ltd, 212 The Glades Shopping Centre High Street',
    'Everything Hunky Dory, 213 The Glades Shopping Centre High Street',
    '214 The Glades Shopping Centre High Street',
    'Hobbs, 219 The Glades Shopping Centre High Street',
    'Bunka, 221 The Glades Shopping Centre High Street',
    'Levis, 222 The Glades Shopping Centre High Street',
    'Phase Eight, 224 The Glades Shopping Centre High Street',
    'Hennes & Mauritz, 226 The Glades Shopping Centre High Street',
    'Jo Malone, 228 The Glades Shopping Centre High Street',
    'Dune, 229 The Glades Shopping Centre High Street',
    '230 The Glades Shopping Centre High Street',
    'Newbie By Kappahl, 231 The Glades Shopping Centre High Street',
    'Unico, 233 The Glades Shopping Centre High Street'
    'Massimo Dutti, 236 The Glades Shopping Centre High Street',
    'Viva La Foto, 237 The Glades Shopping Centre High Street',
    'Zara, 238 The Glades Shopping Centre High Street',
    'Molton Brown, 249 The Glades Shopping Centre High Street',
    '253 The Glades Shopping Centre High Street',
    '254 The Glades Shopping Centre High Street',
    'Seasalt, 255 The Glades Shopping Centre High Street',
    'Holland & Barrett Ltd, 256 The Glades Shopping Centre High Street',
    '258 The Glades Shopping Centre High Street',
    '259 The Glades Shopping Centre High Street',
    '260 The Glades Shopping Centre High Street',
    '262 The Glades Shopping Centre High Street',
    'New Look, 264 The Glades Shopping Centre High Street',
    'H M V UK Ltd, 269 The Glades Shopping Centre High Street',
    'McDonalds Restaurants Ltd, 271 The Glades Shopping Centre High Street',
    '272 The Glades Shopping Centre High Street',
    'Alaska UK, Centre Management Suite, The Glades Shopping Centre High Street',
    'Bubble Citea, The Glades Shopping Centre High Street',
    'Cafe Giardino Ltd, 251-252, The Glades Shopping Centre High Street',
    'Fat Face, 225B, The Glades Shopping Centre High Street',
    'Kaizen, The Glades Shopping Centre High Street',
    'Krispy Kreme Doughnuts, The Glades Shopping Centre High Street',
    'Pandora, 248-250, The Glades Shopping Centre High Street',
    'Super Dry, 265-267, The Glades Shopping Centre High Street',
    'The White Co, 227-228, The Glades Shopping Centre High Street',
    'The White Stuff, 225A, The Glades Shopping Centre High Street',
    'Uniqlo, 225A, The Glades Shopping Centre High Street',
    'Wagamama, The Glades Shopping Centre High Street',
    'Wagamama, Unit 1 A3, The Glades Shopping Centre High Street',
    'Yo Sushi, The Glades Shopping Centre High Street'
),
'BR11DP' => array(
    'Churchill Insurance, Churchill Court, Westmoreland Road',
    'Churchill Insurance Co Ltd, Churchill Court, Westmoreland Road',
    'Deals & Agency Team, Churchill Court, Westmoreland Road',
    'Devitt Insurance, Churchill Court, Westmoreland Road',
    'Direct Line For Business, Churchill Court, Westmoreland Road',
    'Direct Line Group Ltd, Churchill Court, Westmoreland Road',
    'Direct Line Insurance plc, Churchill Court, Westmoreland Road',
    'Dlg Legal Services, Churchill Court, Westmoreland Road',
    'Green Flag, Churchill Court, Westmoreland Road',
    'Green Flag Holdings Ltd, Churchill Court, Westmoreland Road',
    'Nationwide Home Insurance, Churchill Court, Westmoreland Road',
    'Natwest Insurance Services Ltd, Churchill Court, Westmoreland Road',
    'Nig Deals & Agency Team, Churchill Court, Westmoreland Road',
    'Privilege Insurance, Churchill Court, Westmoreland Road',
    'R B S Insurance Direct Line, Churchill Court, Westmoreland Road',
    'Royal Bank Insurance Services, Churchill Court, Westmoreland Road',
    'Royal London, Churchill Court, Westmoreland Road',
    'Ulster Bank Travel Insurance, Churchill Court, Westmoreland Road'
),
'BR11DS' => array(
    'Ark 24 Ltd, 23 Westmoreland Place Masons Hill',
    'Rumours, 23 Westmoreland Place Masons Hill',
    'Seven Seas, 23 Westmoreland Place Masons Hill',
    'Wetherspoons, 23 Westmoreland Place Masons Hill'
),
'BR11EA' => array(
    '26A, High Street',
    '16-18, High Street',
    'Sinclair Hammelton, 2 High Street',
    'Andrew Reeves & Co, 4 High Street',
    'Bromley Cafe, 6 High Street',
    '8 High Street',
    'Subway, 10 High Street',
    'Sameer & Samar UK Ltd, 20 High Street',
    'Fish & Chips, 22 High Street',
    'Traditional Barbers, 24 High Street',
    'Route 66 Vape Station, 26 High Street',
    'Paddy Power, 28 High Street',
    'Leech Vintage, 30 High Street',
    'Toni & Guy, 32 High Street',
    'Medical Mission International, 34 High Street',
    'World Childrens Fund, 34 High Street',
    'Kiwisun Tanning Salon, 36 High Street',
    'J D M Estate Agents, 38 High Street',
    'Nails, 40 High Street',
    'Flat 1, 42 High Street',
    'All Smiles Dental, 42 High Street',
    'William J Wilkinson Opticians, 42 High Street',
    'Dreams, 44 High Street',
    'Dreams, Hanover Place, 44 High Street',
    '46 High Street',
    'Caffe Nero, 12-14, High Street',
    'Calibre Office Furniture & Interiors Ltd, 36-38, High Street'
),
'BR11EG' => array(
    '52D, High Street',
    '52C, High Street',
    '52B, High Street',
    '52A, High Street',
    '66A, High Street',
    '56A, High Street',
    "Rui's Barbers, 48 High Street",
    'M K Law Solicitors Ltd, 50 High Street',
    '52 High Street',
    'Ting Beauty Ltd, 54 High Street',
    '56 High Street',
    'Met-R X, 56 High Street',
    '58 High Street',
    '60 High Street',
    'Unit 4, 62 High Street',
    'Unit 2, 62 High Street',
    'Glasseslab, Unit 3, 62 High Street',
    'Whats New Pussy Cat, Unit 1, 62 High Street',
    'T K Maxx, 64 High Street',
    'Headmasters, 66 High Street',
    'Urban Junction, 68 High Street',
    '70 High Street',
    'Flat D, 70 High Street',
    'Flat C, 70 High Street',
    'Flat B, 70 High Street',
    'Flat A, 70 High Street',
    'Metro Bank, 72-76, High Street'
),
   'RG11EU' => array(
        'Union Street, Reading - More Addresses'   
        'Marketfield Way, Redhill - More Addresses'
        'North Street, Romford - More Addresses'
        'R11u North Promenade Building, Gunwharf Quays, Portsmouth'
    )


  
)


    
?>